// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`
  LOGIN_ATTEMPT
  LOGIN_SUCCESS
  LOGIN_FAILURE

  LOGOUT

  STARTUP

  TEMPERATURE_REQUEST
  TEMPERATURE_RECEIVE
  TEMPERATURE_FAILURE

  INITIATIVE_DATABASE

  KANJI_SEARCH
  KANJI_RECEIVE
  KANJI_NOT_FOUND

  DESK_CREATE
  DESK_ADD_CARD
  DESK_ADD_CARDS
  DESK_SEARCH
  DESK_RECEIVE
  DESKS_SEARCH
  DESKS_RECEIVE
  DESK_NOT_FOUND
`)
